dist: trusty
sudo: required

install:
- echo "deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/fillwave_ext.list
- sudo apt-get update
- sudo apt-get install -yq --no-install-suggests --no-install-recommends --force-yes libglfw3-dev libgles2-mesa-dev

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty
    packages:
    - cmake
    - clang-6.0
    - libc++-dev
    - libc++abi-dev
    - pkg-config
    - libjack-jackd2-dev
    
compiler: clang

before_install:
    - eval "export CXX=clang++-6.0 && export CC=clang-6.0"
before_script:
    - eval "export CXX=clang++-6.0 && export CC=clang-6.0"

script:
- cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-stdlib=libc++"
- make all
- bin/tests
    
